config/routes.rb
# encoding: utf-8

#  Copyright (c) 2012-2021, insieme Schweiz. This file is part of
#  hitobito_insieme and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_insieme.

Rails.application.routes.draw do

  extend LanguageRouteScope

  language_scope do

    resources :groups do
      member do
        scope 'time_record' do
          get '/' => 'time_records#index', as: :time_record
          get ':year/base_information' => 'time_record/base_informations#index',
              as: :time_record_base_information
          get ':year/:report/edit' => 'time_records#edit', as: :edit_time_record_report
          put ':year/:report' => 'time_records#update', as: :time_record_report
          get ':year/:report' => 'time_records#edit' # route required for language switch
        end

        scope 'cost_accounting' do
          get '/' => 'cost_accounting#index', as: :cost_accounting
          get ':year/:report/edit' => 'cost_accounting#edit', as: :edit_cost_accounting_report
          put ':year/:report' => 'cost_accounting#update', as: :cost_accounting_report
          get ':year/:report' => 'cost_accounting#edit' # route required for language switch
        end

        scope 'capital_substrate' do
          get ':year/edit' => 'capital_substrate#edit', as: :edit_capital_substrate
          put ':year' => 'capital_substrate#update', as: :capital_substrate
          get ':year' => 'capital_substrate#edit' # route required for language switch
        end

        get '/statistics' => 'statistics#index', as: :statistics

        get '/controlling'                   => 'controlling#index',             as: :controlling
        get '/controlling/cost_accounting'   => 'controlling#cost_accounting',   as: :cost_accounting_controlling
        get '/controlling/pro_verein'        => 'controlling#pro_verein',        as: :pro_verein_controlling
        get '/controlling/client_statistics' => 'controlling#client_statistics', as: :client_statistics_controlling
        get '/controlling/group_figures'     => 'controlling#group_figures',     as: :group_figures_controlling
        get '/controlling/time_records'      => 'controlling#time_records',      as: :time_records_controlling
        get '/controlling/lufeb_times'       => 'controlling#lufeb_times',       as: :lufeb_times_controlling
        get '/controlling/group_data'        => 'controlling#group_data',        as: :group_data_controlling

        get '/abo_addresses' => 'abo_addresses#index', as: :abo_addresses

        scope module: 'course_reporting' do
          get ':year/aggregations' => 'aggregations#index', as: :aggregations
          get ':year/aggregation/export' => 'aggregations#export', as: :aggregation_export
        end
      end

      resources :events, only: [] do # do not redefine events actions, only add new ones
        collection do
          get 'aggregate_course' => 'events#index', type: 'Event::AggregateCourse'

          scope 'general_cost_allocation' do
            get ':year' => 'event/general_cost_allocations#show', as: :general_cost_allocation
            get ':year/edit' => 'event/general_cost_allocations#edit',
                as: :edit_general_cost_allocation
            put ':year' => 'event/general_cost_allocations#update'
          end
        end

        scope module: 'event' do
          resource :course_record, only: [:edit, :update]
          get 'course_record' => 'course_records#edit' # route required for language switch
        end
      end
    end

    resource :global_value, only: [:show, :edit, :update]

    resources :reporting_parameters, except: :show

  end

end

app/controllers/cost_accounting_controller.rb
# frozen_string_literal: true

#  Copyright (c) 2012-2021, insieme Schweiz. This file is part of
#  hitobito_insieme and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_insieme.

class CostAccountingController < ReportingBaseController
  include Rememberable

  include Featureperioden::Domain
  include Featureperioden::Views

  self.remember_params = [:year]

  helper_method :report, :table, :previous_entry, :section_fields, :gemeinkosten_fields
  delegate :section_fields, :gemeinkosten_fields, to: :table

  before_action :table
  before_action :report, only: [:edit]

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to request.parameters.except(:report).merge({action: index})
  end

  def index
    respond_to do |format|
      format.html
      format.xlsx { render_xlsx }
      format.pdf { render_pdf }
    end
  end

  def edit
  end

  private

  def entry
    @entry ||= CostAccountingRecord.where(group_id: group.id, year: year, report: params[:report])
      .first_or_initialize
  end

  def previous_entry
    @previous_entry ||= entry.class.where(
      group_id: group.id, year: (year - 1), report: params[:report]
    ).first_or_initialize
  end

  def report
    @report ||= entry.report_class || raise(ActiveRecord::RecordNotFound)
  end

  def table
    @table ||= fp_class("CostAccounting::Table").new(group, year)
  end

  def permitted_params
    fields = report.editable_fields
    fields -= ["abgrenzung_dachorganisation"] unless group.is_a?(Group::Dachverein)
    params.require(:cost_accounting_record).permit(fields)
  end

  def render_xlsx
    xlsx = fp_class("Export::Tabular::CostAccounting::List")
      .xlsx(@table.visible_reports.values, group.name, year)
    send_data xlsx, type: :xlsx, filename: export_filename(:xlsx)
  end

  def render_pdf
    pdf = fp_class("Export::Pdf::CostAccounting")
      .new(@table.visible_reports.values, group.name, year)
    send_data pdf.generate, type: :pdf, filename: export_filename(:pdf)
  end

  def export_filename(extension)
    "cost_accounting#{vid}#{bsv}_#{group.name.parameterize}_#{year}.#{extension}"
  end

  def vid
    group.vid.present? && "_vid#{group.vid}" || ""
  end

  def bsv
    group.bsv_number.present? && "_bsv#{group.bsv_number}" || ""
  end
end

app/helpers/cost_accounting_helper.rb
# frozen_string_literal: true

#  Copyright (c) 2012-2020, insieme Schweiz. This file is part of
#  hitobito_insieme and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_insieme.

module CostAccountingHelper
  include Featureperioden::Domain

  # rubocop:todo Metrics/AbcSize
  def cost_accounting_input_fields(f, *fields) # rubocop:disable Metrics/MethodLength,Naming/MethodParameterName
    course_fields = fp_class("CostAccounting::Report::CourseRelated")::COURSE_FIELDS
      .keys.map(&:to_s)
    safe_join(fields) do |field|
      if report.editable_fields.include?(field.to_s)
        f.labeled_fp_input_field(field, addon: t("global.currency"))
      elsif report < fp_class("CostAccounting::Report::CourseRelated") &&
          course_fields.include?(field.to_s)
        # use tag to create field without a name.
        tag.input(type: "hidden",
          id: "cost_accounting_record_#{field}",
          value: table.value_of(report.key, field))
      end
    end
  end
  # rubocop:enable Metrics/AbcSize

  def cost_accounting_input_and_course_fields(f, *fields) # rubocop:disable Metrics/MethodLength,Naming/MethodParameterName,Metrics/AbcSize
    course_fields = fp_class("CostAccounting::Report::CourseRelated")::COURSE_FIELDS
      .keys.map(&:to_s)
    safe_join(fields) do |field|
      if report.editable_fields.include?(field.to_s)
        f.labeled_fp_input_field(field, addon: t("global.currency"))
      elsif report < fp_class("CostAccounting::Report::CourseRelated") &&
          course_fields.include?(field.to_s)
        field_value = table.value_of(report.key, field) || 0.0
        [
          f.labeled_readonly_value(field, value: format_money(field_value)),
          # use tag to create field without a name.
          hidden_field_tag(nil, field_value, id: "cost_accounting_record_#{field}")
        ]
      end
    end
  end

  def cost_account_field_class(field)
    "subtotal" if %w[aufwand_ertrag_ko_re total].include?(field)
  end

  def cost_accounting_reports
    fp_class("CostAccounting::Table")::VISIBLE_REPORTS
  end

  def cost_accounting_report_header(field)
    I18n.translate(
      field,
      scope: [fp_i18n_scope, :headers],
      default: CostAccountingRecord.human_attribute_name(field)
    )
  end

  def base_time_record_group_path(group, _params = {})
    group_path(group) + "/time_record"
  end

  def reporting_nav(label, path, options = {})
    options[:class] += " active" if current_page?(path)
    content_tag(:li, class: "nav-item") do
      link_to(label, path, options)
    end
  end

  def reporting_frozen?
    frozen = GlobalValue.reporting_frozen_until_year
    frozen && year <= frozen
  end

  def reporting_frozen_message
    if reporting_frozen?
      content_tag(:div, t("reporting.frozen_warning"), class: "alert alert-warning")
    end
  end
end

app/helpers/sheet/cost_accounting.rb
# frozen_string_literal: true

#  Copyright (c) 2012-2014, insieme Schweiz. This file is part of
#  hitobito_insieme and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_insieme.

module Sheet
  class CostAccounting < Base
    self.parent_sheet = Sheet::Group
  end
end

app/views/fp2024/cost_accounting/edit.html.haml
-#  Copyright (c) 2012-2020, insieme Schweiz. This file is part of
-#  hitobito_insieme and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_insieme.

- @subtitle = I18n.t('crud.edit.title', model: entry)

= reporting_frozen_message

= crud_form(entry, url: cost_accounting_report_group_path(group, year, entry.report),
                   cancel_url: cost_accounting_group_path(group, year: year),
                   buttons_top: !reporting_frozen?,
                   buttons_bottom: !reporting_frozen?,
                   method: :put,
                   html: { class: 'report', data: { readonly: reporting_frozen? } }) do |f|

  - if report.editable_fields.include?('aufwand_ertrag_fibu')
    = f.labeled_input_field(:aufwand_ertrag_fibu,
                            label: report.aufwand ? t('.aufwand_fibu') : t('.ertrag_fibu'),
                            addon: t('global.currency'))

  - if report.editable_fields.include?('aufteilung_kontengruppen')
    = f.labeled_input_field(:aufteilung_kontengruppen)
    - if previous_entry.aufteilung_kontengruppen.present?
      #cost_accounting_note_copy.hidden
        = f.labeled(:copy_previous_notes, '&nbsp;'.html_safe) do
          = action_button(t('.copy_previous_notes'), '#', :copy)
      #vorheriger-kommentar.hidden
        = previous_entry.aufteilung_kontengruppen

  = cost_accounting_input_fields(f, :abgrenzung_fibu)

  - unless report == fp_class('CostAccounting::Report::DirekteSpendenAusserhalb')
    - factor = report == fp_class('CostAccounting::Report::IndirekteSpenden') ? table.value_of(report.key, 'abgrenzung_factor') : nil
    = f.labeled(:aufwand_ertrag_ko_re, report.aufwand ? t('.aufwand_ko_re') : t('.ertrag_ko_re')) do
      .mt-2#aufwand_ertrag_ko_re{data: { abgrenzung_factor: factor }}

  - if (report.editable_fields & gemeinkosten_fields).present?
    %h3= t('.gemeinkosten')
    = cost_accounting_input_fields(f, *gemeinkosten_fields)
    = f.labeled(:gemeinkosten) do
      .mt-2#gemeinkosten

  - if (report.editable_fields & section_fields).present?
    %h3= t('.kostentraeger')
    = cost_accounting_input_and_course_fields(f, *section_fields)

    = f.labeled(:kostentraeger) do
      .mt-2#kostentraeger

  - if (report.editable_fields & (section_fields + gemeinkosten_fields)).present?
    %hr/
    = f.labeled(:kontrolle) do
      .mt-2#control_value

- content_for(:javascripts) do
  new App.CostAccountingCalculator().updateValues();
  new App.CostAccountingNoteCopier().bind();